name: ci-hit-web

on:
  push:
    paths:
      - "hit-web/**"
      - ".github/workflows/ci-hit-web.yml"
  pull_request:
    paths:
      - "hit-web/**"
      - ".github/workflows/ci-hit-web.yml"

jobs:
  build-hit-web:
    name: Build hit-web frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: hit-web
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: "20"

      - name: Cache npm
        uses: actions/cache@v5
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('hit-web/package-lock.json', 'hit-web/npm-shrinkwrap.json', 'hit-web/package.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: npm install

      - name: Install elm-format
        run: |
          npm install -g elm-format
          echo "$(npm bin -g)" >> $GITHUB_PATH

      - name: Check Elm formatting
        uses: sparksp/elm-format-action@v1
        with:
          elm_files: hit-web/src/
          elm_format: elm-format
          elm_glob: true

      - name: Build
        run: npm run build
