name: ci-hit-cli

on:
  push:
    paths:
      - "hit-cli/**"
      - ".github/workflows/ci-hit-cli.yml"
  pull_request:
    paths:
      - "hit-cli/**"
      - ".github/workflows/ci-hit-cli.yml"

jobs:
  build-hit-cli:
    name: Build hit-cli
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: hit-cli
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: "9.10.2"
          cabal-version: "3.10.1.0"

      - name: Cache cabal store
        uses: actions/cache@v5
        with:
          path: ~/.cabal/store
          key: ${{ runner.os }}-cabal-${{ hashFiles('cabal.project', 'cabal.project.local', '**/*.cabal') }}
          restore-keys: |
            ${{ runner.os }}-cabal-

      - name: Build
        run: |
          cabal update
          cabal build

      - name: Setup HLint
        uses: haskell-actions/hlint-setup@v2

      - name: Run HLint
        uses: haskell-actions/hlint-run@v2

      - name: Check formatting with Ormolu
        uses: haskell-actions/run-ormolu@v16
        with:
          pattern: |
            src/**/*.hs
